server:
  port: 88
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1 #不限制请求大小

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource #配置数据源类型
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://119.45.220.62:4406/wechat-dev?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
    hikari:
      connection-timeout: 30000               # 等待连接池分配连接的最大时间（毫秒），超过这个时长还没有可用的连接，则会抛出SQLException
      minimum-idle: 5                         # 最小连接数
      maximum-pool-size: 20                   # 最大连接数
      auto-commit: true                       # 自动提交
      idle-timeout: 600000                    # 连接超时的最大时长（毫秒），超时则会被释放（retired）
      pool-name: DataSourceHikariCP           # 连接池的名字
      max-lifetime: 18000000                  # 连接池的最大生命时长（毫秒），超时则会被释放（retired）
      connection-test-query: SELECT 1
  data:
    redis:
      host: 119.45.220.62
      port: 5379
      database: 0
  mail:
    default-encoding: UTF-8
    host: smtp.163.com
    port: 465
    username: 15180680576@163.com
    password: EFfQZYE9qfNrUbBm
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            required: true

#日志级别
logging:
  level:
    root: info